#ifndef HAWKTRACER_CONFIG_H_
#define HAWKTRACER_CONFIG_H_

#ifndef HAWKTRACER_TIMELINE_NETWORK_LISTENER_MAX_BUFFER_SIZE
#define HAWKTRACER_TIMELINE_NETWORK_LISTENER_MAX_BUFFER_SIZE 1024
#endif

#ifndef HAWKTRACER_TIMELINE_NETWORK_LISTENER_BUFFER_COUNT
#define HAWKTRACER_TIMELINE_NETWORK_LISTENER_BUFFER_COUNT 128
#endif

#ifndef HAWKTRACER_TIMELINE_BUFFER_SIZE
#define HAWKTRACER_TIMELINE_BUFFER_SIZE 64
#endif

#define HAWKTRACER_PRINT(...)

#endif // HAWKTRACER_CONFIG_H_
