#include "hawktracer/events.h"

HT_DEFINE_EVENT_KLASS(HT_Event, HT_EVENT_TYPE_BASE);
HT_DEFINE_EVENT_KLASS(HT_CallstackBaseEvent, HT_EVENT_TYPE_CALLSTACK_BASE);
HT_DEFINE_EVENT_KLASS(HT_CallstackIntEvent, HT_EVENT_TYPE_CALLSTACK_INT);
HT_DEFINE_EVENT_KLASS(HT_CallstackStringEvent, HT_EVENT_TYPE_CALLSTACK_STRING);
