set(CPACK_GENERATOR "TGZ")
set(CPACK_PACKAGE_VENDOR "Amazon Video")
set(CPACK_PACKAGE_CONTACT "Marcin Kolny <marcin.kolny@gmail.com>")
set(CPACK_PACKAGE_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${PROJECT_VERSION_PATCH}")

include(CPack)
